_target_: cad.models.preprocessing.SDLatentPreconditioning
vae:
  _target_: diffusers.AutoencoderKL.from_pretrained
  pretrained_model_name_or_path: "benjamin-paine/stable-diffusion-v1-5"
input_key: image
output_key: x_0
